---
title: "Raport_silownia"
author: "Tomasz Adrych, Aleksandra Juchniewicz, Patrycja Karpicka"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Identyfikacja Na}
library(readr)
library(dplyr)
library(visdat)
library(naniar)
library(janitor)
#Wczytanie pliku
silownia <- read_csv("silownia_new.csv")
tbl_df(silownia)

silownia <- janitor::clean_names(silownia)

#Liczba brakujących wartości w pliku, kolumnach i wierszach
sum(is.na(silownia))
colSums(is.na(silownia))
rowSums(is.na(silownia))
n_miss(silownia)

#Wykresy brakujących wartości 
vis_miss(silownia)
vis_miss(silownia, cluster=TRUE)

#Wykres powiązań pomiędzy zmiennymi, w których występują wartości NA 
gg_miss_upset(silownia, nsets = 3)

#Wykresy częstości występowania brakujących zmiennych w zależności od płci i rodzaju ćwiczeń
gg_miss_var(silownia, facet = gender)
gg_miss_var(silownia, facet = workout_type)

```

```{r Wykresy pudełkowe przedstawiające wartości odstające}
boxplot(silownia$weight_kg, main = "silownia$weight_kg.")
boxplot(silownia$height_m, main = "silownia$height_kg.")
boxplot(silownia$max_bpm, main = "silownia$max_bpm")
boxplot(silownia$avg_bpm, main = "silownia$avg_bpm")
boxplot(silownia$resting_bpm, main = "silownia$resting_bpm")
boxplot(silownia$session_duration_hours, main = "silownia$session_duration_hours.")
boxplot(silownia$calories_burned, main = "silownia$calories_burned")
boxplot(silownia$fat_percentage, main = "silownia$fat_percentage")
boxplot(silownia$water_intake_liters, main = "silownia$water_intake_liters.")
boxplot(silownia$workout_frequency_days_week, main = "silownia$workout_frequency_days_week")
boxplot(silownia$experience_level, main = "silownia$experience_level")

```

```{r Walidacja}
validate_silownia <- function(silownia) {
  silownia %>%
    mutate(
      age_valid = ifelse(is.na(age) | (age >= 18 & age <= 100), TRUE, FALSE),
      gender_valid = ifelse(gender %in% c("Male", "Female"), TRUE, FALSE),
      weight_valid = ifelse(weight_kg > 35 & weight_kg <= 200, TRUE, FALSE),
      height_valid = ifelse(height_m >= 1 & height_m <= 2.5, TRUE, FALSE),
      max_bpm_valid = ifelse(max_bpm >= 30 & max_bpm <= 220, TRUE, FALSE),
      avg_bpm_valid = ifelse(avg_bpm <= max_bpm & avg_bpm > resting_bpm, TRUE, FALSE),
      resting_bpm_valid = ifelse(resting_bpm >= 30 & resting_bpm <= 100, TRUE, FALSE),
      session_duration_valid = ifelse(session_duration_hours > 0 & session_duration_hours <= 12, TRUE, FALSE),
      calories_burned_valid = ifelse(calories_burned > 0, TRUE, FALSE),
      workout_type_valid = ifelse(is.na(workout_type) | workout_type %in% c("Yoga", "Cardio", "Strength", "HIIT"), TRUE, FALSE),
      fat_percentage_valid = ifelse(fat_percentage >= 6 & fat_percentage <= 100, TRUE, FALSE),
      water_intake_valid = ifelse(water_intake_liters >= 0.5 & water_intake_liters <= 5, TRUE, FALSE),
      workout_frequency_valid = ifelse(workout_frequency_days_week >= 0 & workout_frequency_days_week <= 7, TRUE, FALSE),
      experience_level_valid = ifelse(experience_level >= 1 & experience_level <= 3, TRUE, FALSE),
      bmi_valid = ifelse(is.na(bmi) | (bmi > 10 & bmi <= 50), TRUE, FALSE)
    )
}

# Zastosowanie reguł walidacyjnych
validated_silownia <- validate_silownia(silownia)

# Sprawdzenie 
validation_summary <- validated_silownia %>%
  summarise(
    age_valid = all(age_valid),
    gender_valid = all(gender_valid),
    weight_valid = all(weight_valid),
    height_valid = all(height_valid),
    max_bpm_valid = all(max_bpm_valid),
    avg_bpm_valid = all(avg_bpm_valid),
    resting_bpm_valid = all(resting_bpm_valid),
    session_duration_valid = all(session_duration_valid),
    calories_burned_valid = all(calories_burned_valid),
    workout_type_valid = all(workout_type_valid),
    fat_percentage_valid = all(fat_percentage_valid),
    water_intake_valid = all(water_intake_valid),
    workout_frequency_valid = all(workout_frequency_valid),
    experience_level_valid = all(experience_level_valid),
    bmi_valid = all(bmi_valid)
  )

# Zobrazowanie 
print(validation_summary)


```

```{r Imputacja NA}
library(tidyverse)
library(dlookr)
 
#Imputacja NA dla zmiennej Age
age1 <- round (imputate_na(silownia, age, gender, method = "rpart"))
 summary(age1)

plot(age1)

silownia <- replace_na(data.frame(silownia, age1))
silownia <- silownia %>% 
  mutate(age = age1) %>%
    select(-age1)

#Imputacja NA dla zmiennej BMI
silownia <- silownia %>%
  mutate(
    bmi = if_else(
      is.na(bmi),                                                
      silownia$weight_kg / (silownia$height_m^2),        
      bmi                                                        
      
    )
  )
# zaokrąglam do 2 miejsc po przecinku 
silownia <- silownia %>%
  mutate(bmi = round(bmi, 2))

#Imputacja NA dla zmiennej Workout_Type

library(mice)

#Zamiana zmiennych tekstowych na numeryczne 
#Zmienna Gender: 0 oznacza mężczyznę, 1 kobietę
#Zmienna Workout_Type: 1 to trening siłowy, 2 to trening HIIT, 3 to cardio, a 4 oznacza yogę
silownia$gender <- ifelse (silownia$gender == "Male", 0, 
                           ifelse(silownia$gender == "Female", 1, 2))

silownia$workout_type <- ifelse (silownia$workout_type == "Strength", 1, 
                                 ifelse(silownia$workout_type == "HIIT", 2, 
                                        ifelse(silownia$workout_type == "Cardio", 3,
                                               ifelse(silownia$workout_type == "Yoga", 4, 5))))


#Dane do obliczeń; bez zmiennych Agei i BMI zawierających braki
robocze <- silownia[, 1:15]

#Zmienna Workout_type jako factor
robocze$workout_type <- as.factor(robocze$workout_type)

#####################################################
#Wielowymiarowe wypełnianie przez równania łańcuchowe 

#Tworzenie macierzy zmiennych wykorzystywanych do imputacji
#Wybór zmiennej Workout_type jako tej, która ma zostać uzupełniona
wybrana_zmienna <- is.na(robocze)

#Imputacja danych
wynik <- mice(robocze, where = wybrana_zmienna)

#Podstawienie uzupełnionej zmiennej do zbioru danych
silownia <- complete(wynik)

```